import type { HoverIncident } from '../../shared/types.js';

export const MOCK_INCIDENTS: HoverIncident[] = [
  {
    uuid: 'mock-001',
    date: '2026-04-01',
    attackerCountry: 'JP',
    victimCountry: 'CN',
    details: {
      title: 'JP probe against coastal network',
      summary: 'Simulated reconnaissance traffic against an eastern China public-sector subnet.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-002',
    date: '2026-04-02',
    attackerCountry: 'JP',
    victimCountry: 'CN',
    details: {
      title: 'JP phishing run against logistics vendor',
      summary: 'Credential harvesting campaign aimed at a shipping services supplier.',
      severity: 'low',
    },
  },
  {
    uuid: 'mock-003',
    date: '2026-04-03',
    attackerCountry: 'JP',
    victimCountry: 'CN',
    details: {
      title: 'JP exploit attempt on regional portal',
      summary: 'Automated exploit sweep observed on an exposed web application.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-004',
    date: '2026-04-04',
    attackerCountry: 'JP',
    victimCountry: 'CN',
    details: {
      title: 'JP disruption against telecom edge',
      summary: 'Short-lived disruption attempt targeting a provincial telecom edge node.',
      severity: 'high',
    },
  },
  {
    uuid: 'mock-005',
    date: '2026-04-05',
    attackerCountry: 'US',
    victimCountry: 'CN',
    details: {
      title: 'US scanner burst against cloud tenant',
      summary: 'Simulated scanner wave detected against a China-hosted cloud tenant.',
      severity: 'low',
    },
  },
  {
    uuid: 'mock-006',
    date: '2026-04-06',
    attackerCountry: 'US',
    victimCountry: 'CN',
    details: {
      title: 'US intrusion against manufacturing node',
      summary: 'Privilege escalation attempt aimed at a manufacturing control gateway.',
      severity: 'high',
    },
  },
  {
    uuid: 'mock-007',
    date: '2026-04-07',
    attackerCountry: 'US',
    victimCountry: 'CN',
    details: {
      title: 'US payload delivery to university mail',
      summary: 'Malicious attachment campaign against a university email cluster.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-008',
    date: '2026-04-08',
    attackerCountry: 'US',
    victimCountry: 'CN',
    details: {
      title: 'US lateral movement simulation',
      summary: 'Multi-stage access attempt on a CN enterprise identity provider.',
      severity: 'high',
    },
  },
  {
    uuid: 'mock-009',
    date: '2026-04-09',
    attackerCountry: 'CN',
    victimCountry: 'US',
    details: {
      title: 'CN spearphishing against US contractor',
      summary: 'Targeted phishing emails directed at a US defense-adjacent contractor.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-010',
    date: '2026-04-10',
    attackerCountry: 'CN',
    victimCountry: 'US',
    details: {
      title: 'CN attack against US SaaS control plane',
      summary: 'Simulated account takeover activity against a US SaaS admin endpoint.',
      severity: 'high',
    },
  },
  {
    uuid: 'mock-011',
    date: '2026-04-11',
    attackerCountry: 'RU',
    victimCountry: 'JP',
    details: {
      title: 'RU credential spray against retail portal',
      summary: 'High-volume login attempts observed on a Japanese retail identity service.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-012',
    date: '2026-04-12',
    attackerCountry: 'KR',
    victimCountry: 'SG',
    details: {
      title: 'KR web defacement attempt on finance site',
      summary: 'Short-lived defacement traffic targeted a Singapore financial services landing page.',
      severity: 'low',
    },
  },
  {
    uuid: 'mock-013',
    date: '2026-04-13',
    attackerCountry: 'IN',
    victimCountry: 'AU',
    details: {
      title: 'IN malware delivery to education network',
      summary: 'Suspicious archive attachments were delivered to an Australian university subnet.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-014',
    date: '2026-04-14',
    attackerCountry: 'DE',
    victimCountry: 'GB',
    details: {
      title: 'DE scanning burst against media host',
      summary: 'Automated port scanning observed against a UK-hosted media backend.',
      severity: 'low',
    },
  },
  {
    uuid: 'mock-015',
    date: '2026-04-15',
    attackerCountry: 'BR',
    victimCountry: 'CA',
    details: {
      title: 'BR intrusion attempt on cloud admin',
      summary: 'Privilege escalation and token replay simulated against a Canadian cloud admin console.',
      severity: 'high',
    },
  },
  {
    uuid: 'mock-016',
    date: '2026-04-16',
    attackerCountry: 'FR',
    victimCountry: 'NL',
    details: {
      title: 'FR phishing wave toward logistics staff',
      summary: 'Targeted phishing mails aimed at an enterprise logistics team in the Netherlands.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-017',
    date: '2026-04-17',
    attackerCountry: 'ES',
    victimCountry: 'SE',
    details: {
      title: 'ES bot activity against API gateway',
      summary: 'Bot-driven request flooding hit a Swedish public API gateway.',
      severity: 'low',
    },
  },
  {
    uuid: 'mock-018',
    date: '2026-04-18',
    attackerCountry: 'IT',
    victimCountry: 'NO',
    details: {
      title: 'IT exploit probe on energy dashboard',
      summary: 'An exposed dashboard serving Norwegian energy operators saw exploit probing.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-019',
    date: '2026-04-19',
    attackerCountry: 'PL',
    victimCountry: 'DK',
    details: {
      title: 'PL password attack on SaaS tenant',
      summary: 'Repeated password guessing targeted a Danish SaaS tenant account group.',
      severity: 'high',
    },
  },
  {
    uuid: 'mock-019a',
    date: '2026-04-19',
    attackerCountry: 'RU',
    victimCountry: 'CN',
    details: {
      title: 'RU intrusion burst against China portal',
      summary: 'A critical intrusion attempt was simulated against a Chinese public portal.',
      severity: 'high',
    },
  },
  {
    uuid: 'mock-019b',
    date: '2026-04-19',
    attackerCountry: 'US',
    victimCountry: 'CN',
    details: {
      title: 'US credential theft attempt against China cloud node',
      summary: 'A medium severity credential theft attempt targeted a China-hosted cloud node.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-019c',
    date: '2026-04-19',
    attackerCountry: 'JP',
    victimCountry: 'CN',
    details: {
      title: 'JP scanner sweep against China platform',
      summary: 'Low severity reconnaissance traffic was directed at a Chinese platform endpoint.',
      severity: 'low',
    },
  },
  {
    uuid: 'mock-020',
    date: '2026-04-20',
    attackerCountry: 'TR',
    victimCountry: 'BE',
    details: {
      title: 'TR reconnaissance against government portal',
      summary: 'Low-and-slow reconnaissance against a Belgian government portal was simulated.',
      severity: 'low',
    },
  },
];
