import type { HoverIncident } from '../../shared/types.js';

export const MOCK_INCIDENTS: HoverIncident[] = [
  {
    uuid: 'mock-001',
    date: '2026-04-01',
    attackerCountry: 'JP',
    victimCountry: 'CN',
    details: {
      title: 'JP probe against coastal network',
      summary: 'Simulated reconnaissance traffic against an eastern China public-sector subnet.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-002',
    date: '2026-04-02',
    attackerCountry: 'JP',
    victimCountry: 'CN',
    details: {
      title: 'JP phishing run against logistics vendor',
      summary: 'Credential harvesting campaign aimed at a shipping services supplier.',
      severity: 'low',
    },
  },
  {
    uuid: 'mock-003',
    date: '2026-04-03',
    attackerCountry: 'JP',
    victimCountry: 'CN',
    details: {
      title: 'JP exploit attempt on regional portal',
      summary: 'Automated exploit sweep observed on an exposed web application.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-004',
    date: '2026-04-04',
    attackerCountry: 'JP',
    victimCountry: 'CN',
    details: {
      title: 'JP disruption against telecom edge',
      summary: 'Short-lived disruption attempt targeting a provincial telecom edge node.',
      severity: 'high',
    },
  },
  {
    uuid: 'mock-005',
    date: '2026-04-05',
    attackerCountry: 'US',
    victimCountry: 'CN',
    details: {
      title: 'US scanner burst against cloud tenant',
      summary: 'Simulated scanner wave detected against a China-hosted cloud tenant.',
      severity: 'low',
    },
  },
  {
    uuid: 'mock-006',
    date: '2026-04-06',
    attackerCountry: 'US',
    victimCountry: 'CN',
    details: {
      title: 'US intrusion against manufacturing node',
      summary: 'Privilege escalation attempt aimed at a manufacturing control gateway.',
      severity: 'high',
    },
  },
  {
    uuid: 'mock-007',
    date: '2026-04-07',
    attackerCountry: 'US',
    victimCountry: 'CN',
    details: {
      title: 'US payload delivery to university mail',
      summary: 'Malicious attachment campaign against a university email cluster.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-008',
    date: '2026-04-08',
    attackerCountry: 'US',
    victimCountry: 'CN',
    details: {
      title: 'US lateral movement simulation',
      summary: 'Multi-stage access attempt on a CN enterprise identity provider.',
      severity: 'high',
    },
  },
  {
    uuid: 'mock-009',
    date: '2026-04-09',
    attackerCountry: 'CN',
    victimCountry: 'US',
    details: {
      title: 'CN spearphishing against US contractor',
      summary: 'Targeted phishing emails directed at a US defense-adjacent contractor.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-010',
    date: '2026-04-10',
    attackerCountry: 'CN',
    victimCountry: 'US',
    details: {
      title: 'CN attack against US SaaS control plane',
      summary: 'Simulated account takeover activity against a US SaaS admin endpoint.',
      severity: 'high',
    },
  },
  {
    uuid: 'mock-011',
    date: '2026-04-11',
    attackerCountry: 'RU',
    victimCountry: 'JP',
    details: {
      title: 'RU credential spray against retail portal',
      summary: 'High-volume login attempts observed on a Japanese retail identity service.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-012',
    date: '2026-04-12',
    attackerCountry: 'KR',
    victimCountry: 'SG',
    details: {
      title: 'KR web defacement attempt on finance site',
      summary: 'Short-lived defacement traffic targeted a Singapore financial services landing page.',
      severity: 'low',
    },
  },
  {
    uuid: 'mock-013',
    date: '2026-04-13',
    attackerCountry: 'IN',
    victimCountry: 'AU',
    details: {
      title: 'IN malware delivery to education network',
      summary: 'Suspicious archive attachments were delivered to an Australian university subnet.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-014',
    date: '2026-04-14',
    attackerCountry: 'DE',
    victimCountry: 'GB',
    details: {
      title: 'DE scanning burst against media host',
      summary: 'Automated port scanning observed against a UK-hosted media backend.',
      severity: 'low',
    },
  },
  {
    uuid: 'mock-015',
    date: '2026-04-15',
    attackerCountry: 'BR',
    victimCountry: 'CA',
    details: {
      title: 'BR intrusion attempt on cloud admin',
      summary: 'Privilege escalation and token replay simulated against a Canadian cloud admin console.',
      severity: 'high',
    },
  },
  {
    uuid: 'mock-016',
    date: '2026-04-16',
    attackerCountry: 'FR',
    victimCountry: 'NL',
    details: {
      title: 'FR phishing wave toward logistics staff',
      summary: 'Targeted phishing mails aimed at an enterprise logistics team in the Netherlands.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-017',
    date: '2026-04-17',
    attackerCountry: 'ES',
    victimCountry: 'SE',
    details: {
      title: 'ES bot activity against API gateway',
      summary: 'Bot-driven request flooding hit a Swedish public API gateway.',
      severity: 'low',
    },
  },
  {
    uuid: 'mock-018',
    date: '2026-04-18',
    attackerCountry: 'IT',
    victimCountry: 'NO',
    details: {
      title: 'IT exploit probe on energy dashboard',
      summary: 'An exposed dashboard serving Norwegian energy operators saw exploit probing.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-019',
    date: '2026-04-19',
    attackerCountry: 'PL',
    victimCountry: 'DK',
    details: {
      title: 'PL password attack on SaaS tenant',
      summary: 'Repeated password guessing targeted a Danish SaaS tenant account group.',
      severity: 'high',
    },
  },
  {
    uuid: 'mock-020',
    date: '2026-04-20',
    attackerCountry: 'TR',
    victimCountry: 'BE',
    details: {
      title: 'TR reconnaissance against government portal',
      summary: 'Low-and-slow reconnaissance against a Belgian government portal was simulated.',
      severity: 'low',
    },
  },
  {
    uuid: 'mock-021',
    date: '2026-04-21',
    attackerCountry: 'AE',
    victimCountry: 'CH',
    details: {
      title: 'AE payload staging on document server',
      summary: 'Malicious payload staging activity observed on a Swiss document service.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-022',
    date: '2026-04-22',
    attackerCountry: 'SA',
    victimCountry: 'AT',
    details: {
      title: 'SA web shell attempt on internal app',
      summary: 'An internal Austrian business app saw a simulated web shell deployment attempt.',
      severity: 'high',
    },
  },
  {
    uuid: 'mock-023',
    date: '2026-04-23',
    attackerCountry: 'ZA',
    victimCountry: 'IE',
    details: {
      title: 'ZA scanner sweep against telecom host',
      summary: 'Scanner traffic hit an Irish telecom perimeter host.',
      severity: 'low',
    },
  },
  {
    uuid: 'mock-024',
    date: '2026-04-24',
    attackerCountry: 'EG',
    victimCountry: 'PT',
    details: {
      title: 'EG account takeover exercise on mail',
      summary: 'Account takeover simulation targeted a Portuguese mail platform.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-025',
    date: '2026-04-25',
    attackerCountry: 'AR',
    victimCountry: 'FI',
    details: {
      title: 'AR disruption trial against CDN edge',
      summary: 'A Finnish CDN edge experienced a brief simulated disruption attempt.',
      severity: 'high',
    },
  },
  {
    uuid: 'mock-026',
    date: '2026-04-26',
    attackerCountry: 'CL',
    victimCountry: 'CZ',
    details: {
      title: 'CL phishing campaign on service desk',
      summary: 'Service desk users in the Czech Republic were targeted with spoofed login pages.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-027',
    date: '2026-04-27',
    attackerCountry: 'ID',
    victimCountry: 'HU',
    details: {
      title: 'ID brute force against admin panel',
      summary: 'Repeated brute-force attempts were observed on a Hungarian admin panel.',
      severity: 'high',
    },
  },
  {
    uuid: 'mock-028',
    date: '2026-04-28',
    attackerCountry: 'TH',
    victimCountry: 'RO',
    details: {
      title: 'TH exploit scan on public CMS',
      summary: 'A Romanian public CMS endpoint saw broad exploit scanning.',
      severity: 'low',
    },
  },
  {
    uuid: 'mock-029',
    date: '2026-04-29',
    attackerCountry: 'VN',
    victimCountry: 'GR',
    details: {
      title: 'VN malware drop against finance cluster',
      summary: 'A Greek finance cluster received simulated malware drop traffic.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-030',
    date: '2026-04-30',
    attackerCountry: 'PH',
    victimCountry: 'UA',
    details: {
      title: 'PH access attempt on collaboration portal',
      summary: 'Unauthorized access simulation targeted a Ukrainian collaboration portal.',
      severity: 'high',
    },
  },
  {
    uuid: 'mock-031',
    date: '2026-05-01',
    attackerCountry: 'MY',
    victimCountry: 'SK',
    details: {
      title: 'MY scan burst against customer app',
      summary: 'Customer-facing application infrastructure in Slovakia saw a scan burst.',
      severity: 'low',
    },
  },
  {
    uuid: 'mock-032',
    date: '2026-05-02',
    attackerCountry: 'NZ',
    victimCountry: 'HR',
    details: {
      title: 'NZ spearphishing against contractor',
      summary: 'Contractor mailboxes in Croatia were targeted by a spearphishing run.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-033',
    date: '2026-05-03',
    attackerCountry: 'JP',
    victimCountry: 'LT',
    details: {
      title: 'JP injection trial on booking service',
      summary: 'A Lithuanian booking service saw simulated injection attempts.',
      severity: 'high',
    },
  },
  {
    uuid: 'mock-034',
    date: '2026-05-04',
    attackerCountry: 'US',
    victimCountry: 'LV',
    details: {
      title: 'US credential replay on inventory app',
      summary: 'Credential replay activity was simulated against a Latvian inventory platform.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-035',
    date: '2026-05-05',
    attackerCountry: 'CN',
    victimCountry: 'EE',
    details: {
      title: 'CN scanner pass on edge cluster',
      summary: 'Scanner traffic crossed an Estonian edge cluster without persistence.',
      severity: 'low',
    },
  },
  {
    uuid: 'mock-036',
    date: '2026-05-06',
    attackerCountry: 'RU',
    victimCountry: 'SI',
    details: {
      title: 'RU privilege escalation test on portal',
      summary: 'A Slovenian portal experienced a simulated privilege escalation attempt.',
      severity: 'high',
    },
  },
  {
    uuid: 'mock-037',
    date: '2026-05-07',
    attackerCountry: 'KR',
    victimCountry: 'BG',
    details: {
      title: 'KR phishing lure against HR inbox',
      summary: 'Phishing lures were sent to a Bulgarian HR inbox cluster.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-038',
    date: '2026-05-08',
    attackerCountry: 'IN',
    victimCountry: 'RS',
    details: {
      title: 'IN exploit burst on billing stack',
      summary: 'Billing stack endpoints in Serbia saw a short exploit burst.',
      severity: 'low',
    },
  },
  {
    uuid: 'mock-039',
    date: '2026-05-09',
    attackerCountry: 'DE',
    victimCountry: 'ME',
    details: {
      title: 'DE malware staging on support host',
      summary: 'A Montenegrin support host observed simulated malware staging.',
      severity: 'medium',
    },
  },
  {
    uuid: 'mock-040',
    date: '2026-05-10',
    attackerCountry: 'BR',
    victimCountry: 'IS',
    details: {
      title: 'BR intrusion rehearsal on identity server',
      summary: 'Identity server access rehearsal was run against an Icelandic environment.',
      severity: 'high',
    },
  },
];
